### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by TeddyAristan** [deneb-v/Sudut-Meong#1]
1. Update Employee di Human Resource
-- pas update, di gui tidak berubah tampilan nama rolenya, tetap sama rolenya saat awal "add employee", dan didatabase tidak berubah juga role idnya

2. Add employee sebagai "**promo management**", Di database terdaftar rolenya sebagai "**promo management**", tapi yang tampil setelah login di gui adalah "**Storage Management**"

3.  Add employee sebagai "**human resource**", Di database terdaftar rolenya sebagai "**human resource**", tapi yang tampil setelah login adalah "**Cashier**"

4. Add employee sebagai "**manager**", Di database terdaftar rolenya sebagai "**manager**", tapi yang tampil setelah login adalah "**tidak ada/kosong**"

5. Add employee sebagai "**storage management**", Di database terdaftar rolenya sebagai "**storage management**", tapi yang tampil setelah login adalah "**tidak ada/kosong**"

6. Add employee sebagai "**promo management**", Di database terdaftar rolenya sebagai "**promo management**", tapi yang tampil setelah login adalah "**tidak ada/kosong**"

7. Add employee sebagai "**cashier**", Di database terdaftar rolenya sebagai "**cashier**", tapi yang tampil setelah login adalah "**tidak ada/kosong**"

8. Promo management, 
-- pada create new voucher, divalidasi, diskon berhasil dicreate < 1% yang seharusnya 1-100% saja
-- pada update voucher, di gui maupun database tidak berubah datanya saat di update dan validasi nya pun tidak bekerja di diskon maupun di date
-- pada delete voucher, tidak terjadi apa2 baik di gui maupun di database

note : gatau kenapa untuk employee yang terdaftar di database idnya > 5 tampilan kosong

**Comment by deneb-v** [comment]
Fixed, coba di cek lagi
